name: Spelling

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  codespell:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          check_hidden: false
          path: src include tests docs
